### ISSUE TITLE
Double application

### ISSUE THREAD

**Issue by mateobosco** [Todd-Davies/ProgressWheel#57]
After adding the project as a dependency, when I run my application in an Android device it installs two applications, one of them is the actual application and the other one is the sample app from Progress Wheel. I cant figure out how to solve this.
![device-2015-07-20-150843](https://cloud.githubusercontent.com/assets/8311701/8783320/763514ca-2ef1-11e5-86ec-a19bf2f4d39e.png)

**Comment by RDengue** [comment]
add the project as module ,next clear the intent-filter in AndroidManifest in module ProgressWheel . I hope help you . regards

**Comment by mateobosco** [comment]
That was the way that I was doing it before but now i have it as a dependency in the build.gradle

 repositories {
        maven { url "https://jitpack.io" }
    }

    dependencies {
        compile 'com.github.Todd-Davies:ProgressWheel:1.0'
    }

is there a way to solve this?

**Comment by Orbycius** [comment]
@mateobosco unfortunately until @Todd-Davies removes the launcher filter from the manifest you will have this issue since an app can only have one launcher filter (at least if you only want one icon).

However there's something you can do about it without having to add the project as a module.

Basically gradle merges all the manifests into one that you can find in build/intermediates/manifests/full and you can "override" the activity causing this issue. You only need to add the activity to your app manifest and remove the filters.

`<activity`
 `       android:name="com.todddavies.components.progressbar.Main"`
  `      android:label="@string/app_name" >`
   `     <intent-filter tools:node="removeAll" />`
   ` </activity>`

Add that to your Manifest and will be ok.

**Comment by Todd-Davies** [comment]
If it's urgent, you can submit a pull request. Otherwise, I'll get around to doing this at some point. Thanks!

**Comment by Todd-Davies** [comment]
Hey @mateobosco, @Orbycius, this should be fixed now :)

**Comment by sangrime** [comment]
Is it fixed? I still can see two apps..

**Comment by Todd-Davies** [comment]
Are you using the latest version @sangrime? This should be fixed in e6241f97a.

**Comment by hoseinit** [comment]
@Todd-Davies Hi, By declaring the library version 1.0 in Gradle I still see two applications. How to use the latest version in gradle method?

**Comment by o-ayoub** [comment]
Hello
How can I reslove this issue: 
Failed to resolve: com.github.Todd-Davies:ProgressWheel:1.2 

Thanks

**Comment by AkioAlex0817** [comment]
I also can not resolve com.github.Todd-Davies:ProgressWheel:1.2

**Comment by choyisus** [comment]
this theme is from 2015 four years a go :( 
where is 
todd davies

**Comment by Todd-Davies** [comment]
Hey, sorry for my inactivity; I'm rather busy and this library is a legacy from another part of my life. Finding the time to maintain it properly isn't really feasible right now.

My best advice would be to avoid using the library in the first place; it was created specifically for old versions of Android (~version 2), which according to [1] has ~0.2% market share right now. Simply using the built-in Android progress spinner is likely to be far more stable and compatible, and I'm sure there must be more up-to-date libraries if you want something more fancy.

I'll do my best to fix the dependencies/build in future, but can't promise when.

Have a lovely day!

[1] https://developer.android.com/about/dashboards

**Comment by choyisus** [comment]
thanks for coming :) im a fan of you :)

**Comment by choyisus** [comment]
> Hey, sorry for my inactivity; I'm rather busy and this library is a legacy from another part of my life. Finding the time to maintain it properly isn't really feasible right now.
> 
> My best advice would be to avoid using the library in the first place; it was created specifically for old versions of Android (~version 2), which according to [1] has ~0.2% market share right now. Simply using the built-in Android progress spinner is likely to be far more stable and compatible, and I'm sure there must be more up-to-date libraries if you want something more fancy.
> 
> I'll do my best to fix the dependencies/build in future, but can't promise when.
> 
> Have a lovely day!
> 
> [1] https://developer.android.com/about/dashboards

hey todd the fix of two apk's work ?
if not work the wheel i can remove from my apk how ////thanks

**Comment by SalilLuley** [comment]
I resolved this issue by donwngrading the version to 
**implementation 'com.github.Todd-Davies:ProgressWheel:1.0'**

**Cheers**
